# Generated by Django 3.1 on 2020-08-16 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LiftoffApp', '0003_session_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_number']},
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique_for_date=True),
        ),
    ]
